port: 8080
url: ws://b-mocks.dev.app.getbaraka.com:9989
threadPoolSize: 10
candles: [1:SECONDS, 5:SECONDS, 10:SECONDS, 15:SECONDS, 30:SECONDS,
          1:MINUTES, 5:MINUTES, 10:MINUTES, 15:MINUTES, 30:MINUTES,
          1:HOURS]